### ISSUE TITLE
cpuid_amd64.s:29 illegal instruction

### ISSUE THREAD

**Issue by logrusorgru** [klauspost/cpuid#5]
$ go test

```
SIGILL: illegal instruction
PC=0x497234 m=0

goroutine 67 [running]:
github.com/klauspost/cpuid.asmXgetbv(0x6874754100000000, 0x4080000600f01, 0x178bfbff1e98220b, 0xd0047edfa, 0x4080000000001, 0x408001e98220b, 0x2000078017f1, 0x47dd77, 0x15, 0x0, ...)
        /home/anoobis/PRO/go/src/github.com/klauspost/cpuid/cpuid_amd64.s:29 +0x4 fp=0xc82009db50 sp=0xc82009db48
github.com/klauspost/cpuid.support(0x15)
        /home/anoobis/PRO/go/src/github.com/klauspost/cpuid/cpuid.go:793 +0x21a fp=0xc82009db90 sp=0xc82009db50
github.com/klauspost/cpuid.Detect()
        /home/anoobis/PRO/go/src/github.com/klauspost/cpuid/cpuid.go:191 +0x97 fp=0xc82009dbb8 sp=0xc82009db90
github.com/klauspost/cpuid.TestMocks(0xc8200a2360)
        /home/anoobis/PRO/go/src/github.com/klauspost/cpuid/mockcpu_test.go:147 +0x70e fp=0xc82009df58 sp=0xc82009dbb8
testing.tRunner(0xc8200a2360, 0x6b9e30)
        /opt/go/src/testing/testing.go:456 +0x98 fp=0xc82009df90 sp=0xc82009df58
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82009df98 sp=0xc82009df90
created by testing.RunTests
        /opt/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x61c410, 0x6b9860, 0x3f, 0x3f, 0x1)
        /opt/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820047f08, 0xc82000a7d0)
        /opt/go/src/testing/testing.go:494 +0x70
main.main()
        github.com/klauspost/cpuid/_test/_testmain.go:178 +0x116

rax    0x2000038017f1
rbx    0x497230
rcx    0x0
rdx    0x61c3e8
rdi    0x40800
rsi    0x40800
rbp    0x600f01
rsp    0xc82009db48
r8     0xc82009d8e0
r9     0x2c
r10    0x0
r11    0x0
r12    0x2
r13    0x619d4d
r14    0x2
r15    0x8
rip    0x497234
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
exit status 2
FAIL    github.com/klauspost/cpuid      0.076s
```

OS: Linux  3.13.0-52-generic  x86_64
CPU: AMD64 Athlon X2
go version go1.5 linux/amd64

**Comment by klauspost** [comment]
Thanks for the report.

Luckily it was only the test causing the crash. 

To run the tests it emulates 235 different CPU's, however the XGETBV was not emulated, so that was run on your machine. Since the mocked CPU said XGETBV was supported, the XGETBV instruction was run on your machine, which didn't support it.

The XGETBV is now "emulated" as well, which makes the tests even stronger.

Again, thanks for the report, if you update it should work now.
