### ISSUE TITLE
FTBFS issue on arm64

### ISSUE THREAD

**Issue by rogers0** [klauspost/cpuid#53]
Latest 1.3.0 release fails on arm64, while previous 1.2.5 release built well:
- https://tests.reproducible-builds.org/debian/rb-pkg/unstable/arm64/golang-github-klauspost-cpuid.html

Build log of arm64:
- https://tests.reproducible-builds.org/debian/rbuild/unstable/arm64/golang-github-klauspost-cpuid_1.3.0+ds-1.rbuild.log.gz

```
   dh_auto_test -O--buildsystem=golang
	cd obj-aarch64-linux-gnu && go test -vet=off -v -p 8 github.com/klauspost/cpuid
SIGILL: illegal instruction
PC=0x118520 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
github.com/klauspost/cpuid.getProcFeatures(0x140760, 0x400018c210, 0x16d743, 0xc, 0x4000068ed8, 0x10cef4, 0x28a860, 0x10cef0, 0x4000068ee8, 0x4f78c, ...)
	/build/1st/golang-github-klauspost-cpuid-1.3.0+ds/obj-aarch64-linux-gnu/src/github.com/klauspost/cpuid/cpuid_arm64.s:15 fp=0x4000068e90 sp=0x4000068e90 pc=0x118520
github.com/klauspost/cpuid.addInfo(0x28a860)
	/build/1st/golang-github-klauspost-cpuid-1.3.0+ds/obj-aarch64-linux-gnu/src/github.com/klauspost/cpuid/detect_arm64.go:42 +0x20 fp=0x4000068ec0 sp=0x4000068e90 pc=0x10d620
github.com/klauspost/cpuid.Detect()
	/build/1st/golang-github-klauspost-cpuid-1.3.0+ds/obj-aarch64-linux-gnu/src/github.com/klauspost/cpuid/cpuid.go:289 +0x70 fp=0x4000068ee0 sp=0x4000068ec0 pc=0x10cf80
github.com/klauspost/cpuid.init.0()
	/build/1st/golang-github-klauspost-cpuid-1.3.0+ds/obj-aarch64-linux-gnu/src/github.com/klauspost/cpuid/cpuid.go:272 +0x24 fp=0x4000068ef0 sp=0x4000068ee0 pc=0x10cef4
runtime.doInit(0x2731c0)
	/usr/lib/go-1.14/src/runtime/proc.go:5420 +0x9c fp=0x4000068f30 sp=0x4000068ef0 pc=0x4f78c
runtime.doInit(0x272320)
	/usr/lib/go-1.14/src/runtime/proc.go:5415 +0x58 fp=0x4000068f70 sp=0x4000068f30 pc=0x4f748
runtime.main()
	/usr/lib/go-1.14/src/runtime/proc.go:190 +0x1b8 fp=0x4000068fd0 sp=0x4000068f70 pc=0x42838
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4000068fd0 sp=0x4000068fd0 pc=0x6f8b4

r0      0x28a860
r1      0x4000068380
r2      0x4000068ec0
r3      0x5
r4      0x140760
r5      0x0
r6      0x16d743
r7      0xa
r8      0xf
r9      0x4
r10     0x0
r11     0xd
r12     0x1
r13     0x802aaaa00aaaa
r14     0xf8
r15     0x0
r16     0x34
r17     0x68
r18     0x0
r19     0xd0
r20     0x4000068da8
r21     0xffffc1ed5840
r22     0x4000002000
r23     0x0
r24     0x0
r25     0x0
r26     0x273210
r27     0x28a8e8
r28     0x4000000180
r29     0x4000068e88
lr      0x10d620
sp      0x4000068e90
pc      0x118520
fault   0x0
FAIL	github.com/klauspost/cpuid	0.005s
```

**Comment by klauspost** [comment]
Addressed in #52
